### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by zjfsdnu** [jruit/babel-tutorial#1]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle babel03@1.0.0~predev: babel03@1.0.0
6 info lifecycle babel03@1.0.0~dev: babel03@1.0.0
7 verbose lifecycle babel03@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle babel03@1.0.0~dev: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/zjf/work/git/babel-tutorial/babel03/node_modules/.bin:/home/zjf/go/bin:/usr/local/go/bin:/home/zjf/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/dotnet2.1
9 verbose lifecycle babel03@1.0.0~dev: CWD: /home/zjf/work/git/babel-tutorial/babel03
10 silly lifecycle babel03@1.0.0~dev: Args: [ '-c', 'npx webpack a.js -o b.js' ]
11 silly lifecycle babel03@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle babel03@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: babel03@1.0.0 dev: `npx webpack a.js -o b.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid babel03@1.0.0
15 verbose cwd /home/zjf/work/git/babel-tutorial/babel03
16 verbose Linux 5.4.0-29-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error babel03@1.0.0 dev: `npx webpack a.js -o b.js`
22 error Exit status 1
23 error Failed at the babel03@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

去掉package-lock.json文件即可解决

**Comment by zjfsdnu** [comment]
建议删除生成的文件 比如b.js、compiled.js等 只保留必要的文件
